alias gain='mp3gain -r *.mp3'
alias du='du -kh'
alias df='df -kh'
alias mkdir='mkdir -p -v'
alias rm='rm -r'
alias cdtemp='cd $(mktemp --dir)'
alias pushtemp='pushd . && cdtemp'
alias chalias='nano ~/.bash_aliases'
alias title='mocp -Q%title'
alias mkreport='mkdir report && cd report && mkdir res && cp ~/Schoolwork/report_template.tex $(pwd)/report.tex'
alias shutdown='shutdown now'
alias valgrind='valgrind --vgdb=yes --vgdb-error=0'
