#!/bin/bash

backupUrl=raspberrypi.localdomain
logFile=/home/luke/.backuplog

function log {
  echo $@ >> $logFile
}

function checkReturn {
  retVal=$?
  if [[ $retVal != 0 ]]; then {
    log $@
    exit $retVal
  } fi
}

notify-send -i /home/luke/.icons/backupIco.png "running backup"
date > /home/luke/.backuplog

ping -qc 1 $backupUrl >/dev/null 2>&1
checkReturn "cannot access backup loc"

rdiff-backup -v 5 \
  --include '/home/luke/.gnupg/' \
  --include '/home/luke/.password-store/' \
  --include '/home/luke/.minecraft/' \
  --exclude '/home/luke/.*' \
  --exclude '/home/luke/Pi/' \
  --exclude '/home/luke/Phone/' \
  --exclude '/home/luke/tmp' \
  --exclude '/home/luke/VideoDecodeStats' \
  --exclude '/home/luke/databases-incognito' \
  --exclude-regexp '/home/luke/Workspace/.*/node_modules/.*' \
  --exclude-regexp '/home/luke/Workspace/.*/__pycache__/.*' \
  /home/luke/ \
  luke@$backupUrl::/home/luke/Backups \
  >> $logFile 2>&1
checkReturn "backup failed"

log "done"
