#!/bin/bash
notify-send -i /home/luke/.icons/backupIco.png "running backup"
date >> /home/luke/.backuplog
rdiff-backup --exclude '/home/luke/Dropbox/' --exclude '/home/luke/Pi/' --exclude '/home/luke/Downloads/' --include '/home/luke/.password-store' --exclude '/home/luke/.*' /home/luke/ luke@lukegrehan.com::/home/luke/Backups
