#!/bin/bash
notify-send -i /home/luke/.icons/backupIco.png "running backup"
date > /home/luke/.backuplog
rdiff-backup -v 6 \
  --include '/home/luke/.gnupg/' \
  --include '/home/luke/.password-store/' \
  --include '/home/luke/.minecraft/' \
  --exclude '/home/luke/.*' \
  --exclude '/home/luke/Pi/' \
  --exclude '/home/luke/Phone/' \
  --exclude '/home/luke/tmp' \
  /home/luke/ \
  luke@lukegrehan.com::/home/luke/Backups >> /home/luke/.backuplog
