#!/bin/env python

import xmltodict
import json

def xmltojson(xml):
    return json.dumps(xmltodict.parse(xml))

if __name__ == '__main__':
    import fileinput
    try:
        with fileinput.input() as f:
            xml = "\n".join(line for line in f)
        dict = xmltodict.parse(xml)
        json = json.dumps(dict)
        print(json)
    except Exception as e:
        import sys
        print(e)
        sys.exit(1)
